name: Documentation QA
on: [pull_request, push]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.35"

      - name: Build documentation site
        run: mdbook build --dest-dir ./public

      - name: Spell check sources
        run: |
          pip install codespell
          codespell ./src/**/*.md --skip="*.css,*.svg" --ignore-words-list="async,config"

      - name: Link validation
        uses: lycheeverse/lychee-action@v1 # Update version if necessary (e.g., v2)
        with:
          args: --verbose --no-progress "./public/**/*.html"

      - name: Accessibility audit setup (Puppeteer workaround)
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth static-sitemap-cli pa11y pa11y-ci serve

      - name: Accessibility audit execution (with Puppeteer fix)
        env:
          PUPPETEER_SKIP_DOWNLOAD_CHROMIUM: true
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
          PUPPETEER_ARGS: --no-sandbox
          PORT: 3000
        run: |
          sscli -b http://localhost:${PORT}/sitemap.xml \
                || echo "Error generating sitemap."

          npx serve ./public -l ${PORT} &

          for i in {1..10}; do 
            curl http://localhost:${PORT}/sitemap.xml \
              && break || echo "Waiting..." && sleep 2; 
            done 

            if curl http://localhost:${PORT}/sitemap.xml; then 
              npx pa11y-ci --sitemap http://localhost:${PORT}/sitemap.xml;
            else 
              echo "Sitemap not found."
              exit 1;
            fi

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.npm
          key: ${{ runner.os }}-deps-${{ hashFiles('**/Cargo.lock') }}
