name: Documentation QA
on: [pull_request, push]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.35"

      - name: Build documentation site
        run: mdbook build --dest-dir ./public

      - name: Spell check sources
        run: |
          pip install codespell
          codespell ./src/**/*.md --skip="*.css,*.svg" --ignore-words-list="async,config"

      - name: Link validation
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress "./public/**/*.html"

      - name: Accessibility audit
        run: |
          npm i -g static-sitemap-cli
          sscli -b http://localhost:3000 -r public

          npm install -g pa11y pa11y-ci serve
          npx serve ./public &

          # Wait for the server to be available
          for i in {1..10}; do
            curl -s --head http://localhost:3000/sitemap.xml | grep "200 OK" && break
            echo "Waiting for server..."
            sleep 2
          done

          # Verify sitemap exists before running pa11y-ci
          if curl -s --head http://localhost:3000/sitemap.xml | grep "200 OK"; then
            PA11Y_OPTS="--chrome-launcher --no-sandbox"
            pa11y-ci --sitemap http://localhost:3000/sitemap.xml $PA11Y_OPTS
          else
            echo "Error: sitemap.xml not found"
            exit 1
          fi

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.npm
          key: ${{ runner.os }}-deps-${{ hashFiles('**/Cargo.lock') }}
